package shared

val PLAYER_INITIAL_HP = 500
val PLAYER_DEFENSE = 30
val ATTACK_HIT = 110
val SKILL_HIT = 100
val MAGIC_HIT = 70
val GOLEM_HIT = 75
val GOLEM_FLEE = 20
val GOBLIN_HIT = 85
val GOBLIN_FLEE = 40
val SLIME_HIT = 95
val SLIME_FLEE = 30
val MAX_GOLEM_LEVEL = 5
val MAX_GOBLIN_LEVEL = 7
val MAX_SLIME_LEVEL = 9